dns:
  upstream_dns:
    - '#cloudflare'
    - https://cloudflare-dns.com/dns-query
    - '#tls://1.1.1.1'
    - '#tls://1.0.0.1'
    - '#google'
    - '#https://dns.google/dns-query'
    - '#tls://dns.google'
    - '#tls://8.8.8.8'
    - '#tls://8.8.4.4'
    - '#Quad9'
    - https://dns.quad9.net/dns-query
    - '#tls://dns.quad9.net'
    - '#tls://9.9.9.9'
    - '#tls://149.112.112.112'
    - '#Yandex'
    - https://common.dot.dns.yandex.net/dns-query
    - '#tls://common.dot.dns.yandex.net'
    - '#tls://77.88.8.8'
    - '#tls://77.88.8.1'
    - '#AdGuard'
    - https://dns.adguard-dns.com/dns-query
    - '#https://unfiltered.adguard-dns.com/dns-query'
    - '#tls://dns.adguard-dns.com'
    - '#tls://unfiltered.adguard-dns.com'
    - '#tls://94.140.14.14'
    - '#tls://94.140.15.15'
    - '#Comss.one'
    - https://dns.comss.one/dns-query
    - '#tls://dns.comss.one'
    - '#OpenDNS'
    - https://doh.opendns.com/dns-query
    - '#tls://dns.opendns.com'
    - '#tls://208.67.222.222'
    - '#tls://208.67.220.220'
    - '#Mullvad'
    - '#https://dns.mullvad.net/dns-query'
    - '#tls://dns.mullvad.net'
    - '#themoviedb.org domain bypass'
    - '[/themoviedb.org/]https://dns10.quad9.net/dns-query'
    - '#tmdb.org domain bypass'
    - '[/tmdb.org/]https://dns10.quad9.net/dns-query'
    - '[/image.tmdb.org/]https://dns10.quad9.net/dns-query'
  local_ptr_upstreams:
    - 172.17.0.1
    - 172.18.0.1
    - 172.20.0.1
    - 172.21.0.1
    - 172.22.0.1
filters:
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://adaway.org/hosts.txt
    name: AdAway Default Blocklist
    id: 2
  - enabled: true
    url: https://someonewhocares.org/hosts/zero/hosts
    name: Dan Pollock's List
    id: 1645953624
  - enabled: true
    url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
    name: Game Console Adblock List
    id: 1645953625
  - enabled: true
    url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
    name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
    id: 1645953627
  - enabled: true
    url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
    name: Peter Lowe's List
    id: 1645953628
  - enabled: true
    url: https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
    name: Scam Blocklist by DurableNapkin
    id: 1645953630
  - enabled: true
    url: https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts
    name: The Big List of Hacked Malware Web Sites
    id: 1645953631
  - enabled: true
    url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
    name: NoCoin Filter List
    id: 1645953632
  - enabled: true
    url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    name: WindowsSpyBlocker - Hosts spy rules
    id: 1645953633
  - enabled: true
    url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt
    name: Dandelion Sprout's Anti-Malware List
    id: 1645953634
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
    name: Malicious URL Blocklist (URLHaus)
    id: 1690839331
user_rules:
  - '@@||static.lostfilm.top^$important'
  - '@@||static.lostfilm.tv^$important'
  - '@@||static.lostfilm.life^$important'
  - '@@||startup.mobile.yandex.net^$important'
  - '@@||arc.msn.com^$important'
  - '@@||metrics.icloud.com^$important'
  - '@@||g.live.com^$important'
  - '@@||log-upload-os.hoyoverse.com^$important'
filtering:
  rewrites:
    # null (16)
    - domain: wired.nul.external
      answer: reserved
      enabled: false
    - domain: mobile.nul.external
      answer: reserved
      enabled: false
    - domain: router.nul.internal
      answer: sun.nul.internal
      enabled: false
    - domain: sun.nul.internal
      answer: reserved
      enabled: false
    - domain: nemesis.nul.internal
      answer: reserved
      enabled: false
    - domain: '*.app.nul.internal'
      answer: terra.nul.internal
      enabled: false
    - domain: terra.nul.internal
      answer: reserved
      enabled: false
    - domain: terra.internal
      answer: terra.yaf.internal
      enabled: true
    - domain: '*.terra.nul.internal'
      answer: terra.nul.internal
      enabled: false
    - domain: phaeton.nul.internal
      answer: reserved
      enabled: false
    - domain: phaeton.internal
      answer: phaeton.yaf.internal
      enabled: true
    - domain: vesta.nul.internal
      answer: reserved
      enabled: false
    - domain: vesta.internal
      answer: vesta.nul.internal
      enabled: false
    - domain: '*.vesta.nul.internal'
      answer: vesta.nul.internal
      enabled: false
    - domain: victoria.nul.internal
      answer: reserved
      enabled: false
    - domain: victoria.internal
      answer: victoria.nul.internal
      enabled: false
    - domain: '*.victoria.nul.internal'
      answer: victoria.nul.internal
      enabled: false
    - domain: jupiter.nul.internal
      answer: reserved
      enabled: false
    - domain: jupiter.internal
      answer: jupiter.yaf.internal
      enabled: true
    - domain: mars.nul.internal
      answer: reserved
      enabled: false
    - domain: mars.internal
      answer: mars.yaf.internal
      enabled: true
    - domain: saturn.nul.internal
      answer: reserved
      enabled: false
    - domain: saturn.internal
      answer: saturn.yaf.internal
      enabled: true
    - domain: uranus.nul.internal
      answer: reserved
      enabled: false
    - domain: uranus.internal
      answer: uranus.yaf.internal
      enabled: true
    - domain: eris.nul.internal
      answer: reserved
      enabled: false
    - domain: hygiea.nul.internal
      answer: reserved
      enabled: false
    - domain: hebe.nul.internal
      answer: reserved
      enabled: false
    - domain: inky.nul.internal
      answer: reserved
      enabled: false
    - domain: inky.internal
      answer: inky.yaf.internal
      enabled: true
    # vasilkovo (17)
    - domain: point.vas.external
      answer: 192.168.1.1
      enabled: true
    - domain: yota.vas.external
      answer: 192.168.8.1
      enabled: true
    - domain: router.vas.internal
      answer: ganymede.vas.internal
      enabled: true
    - domain: ganymede.vas.internal
      answer: 172.17.0.1
      enabled: true
    - domain: callisto.vas.internal
      answer: 172.17.0.2
      enabled: true
    - domain: himalia.vas.internal
      answer: 172.17.0.20
      enabled: true
    - domain: thebe.vas.internal
      answer: 172.17.0.21
      enabled: true
    - domain: amalthea.vas.internal
      answer: 172.17.0.4
      enabled: true
    - domain: '*.app.vas.internal'
      answer: io.vas.internal
      enabled: true
    - domain: io.vas.internal
      answer: 172.17.2.10
      enabled: true
    - domain: io.internal
      answer: io.vas.internal
      enabled: true
    - domain: '*.io.vas.internal'
      answer: io.vas.internal
      enabled: true
    - domain: europa.vas.internal
      answer: 172.17.2.11
      enabled: true
    - domain: europa.internal
      answer: europa.vas.internal
      enabled: true
    - domain: '*.europa.vas.internal'
      answer: europa.vas.internal
      enabled: true
    - domain: elara.vas.internal
      answer: 172.17.4.12
      enabled: true
    - domain: leda.yaf.internal
      answer: 172.17.4.110
      enabled: true
    - domain: ananke.yaf.internal
      answer: 172.17.4.11
      enabled: true 
    # vasilkovo-new (17)
    - domain: point.vas.outer
      answer: 192.168.1.1
      enabled: true
    - domain: yota.vas.outer
      answer: 192.168.8.1
      enabled: true
    - domain: router.vas.local
      answer: ganymede.vas.local
      enabled: true
    - domain: ganymede.vas.local
      answer: 172.17.0.1
      enabled: true
    - domain: callisto.vas.local
      answer: 172.17.0.2
      enabled: true
    - domain: himalia.vas.local
      answer: 172.17.0.20
      enabled: true
    - domain: thebe.vas.local
      answer: 172.17.0.21
      enabled: true
    - domain: amalthea.vas.local
      answer: 172.17.0.4
      enabled: true
    - domain: '*.app.vas.local'
      answer: io.vas.local
      enabled: true
    - domain: io.vas.local
      answer: 172.17.2.10
      enabled: true
    - domain: io.local
      answer: io.vas.local
      enabled: true
    - domain: '*.io.vas.local'
      answer: io.vas.local
      enabled: true
    - domain: europa.vas.local
      answer: 172.17.2.11
      enabled: true
    - domain: europa.local
      answer: europa.vas.local
      enabled: true
    - domain: '*.europa.vas.local'
      answer: europa.vas.local
      enabled: true
    - domain: elara.vas.local
      answer: 172.17.4.12
      enabled: true
    - domain: leda.yaf.local
      answer: 172.17.4.110
      enabled: true
    - domain: ananke.yaf.local
      answer: 172.17.4.11
      enabled: true
    # chanovo (18)
    - domain: router.cha.internal
      answer: titan.cha.internal
      enabled: true
    - domain: titan.cha.internal
      answer: 172.18.0.1
      enabled: true
    - domain: rhea.cha.internal
      answer: 172.18.0.2
      enabled: true
    - domain: dione.cha.internal
      answer: 172.18.0.3
      enabled: true
    - domain: '*.app.cha.internal'
      answer: mimas.cha.internal
      enabled: true
    - domain: mimas.cha.internal
      answer: 172.20.13.18
      enabled: true
    - domain: mimas.internal
      answer: mimas.cha.internal
      enabled: true
    - domain: '*.mimas.cha.internal'
      answer: mimas.cha.internal
      enabled: true
    # yasenevod (19)
    - domain: mts.yad.external
      answer: 192.168.1.1
      enabled: true
    - domain: router.yad.internal
      answer: phobos.yad.internal
      enabled: true
    - domain: phobos.yad.internal
      answer: 172.21.0.1
      enabled: true
    # yasenevof (20)
    - domain: mts.yaf.external
      answer: 192.168.1.1
      enabled: true
    - domain: yota.yaf.external
      answer: 192.168.0.1
      enabled: true
    - domain: router.yaf.internal
      answer: titania.yaf.internal
      enabled: true
    - domain: titania.yaf.internal
      answer: 172.20.0.1
      enabled: true
    - domain: oberon.yaf.internal
      answer: 172.20.0.2
      enabled: true
    - domain: ariel.yaf.internal
      answer: 172.20.2.10
      enabled: true
    - domain: ariel.internal
      answer: ariel.yaf.internal
      enabled: true
    - domain: '*.ariel.yaf.internal'
      answer: 172.20.2.10
      enabled: true
    - domain: '*.app.yaf.internal'
      answer: 172.20.2.10
      enabled: true
    - domain: terra.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: '*.terra.yaf.internal'
      answer: 172.20.2.12
      enabled: true
    - domain: phaeton.yaf.internal
      answer: 172.20.2.201
      enabled: true
    - domain: vaultwarden.app.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: nextcloud.app.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: calibre.app.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: qbittorrent.app.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: resilio.app.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: hplip.app.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: jellyfin.app.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: radarr.app.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: sonarr.app.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: jackett.app.yaf.internal
      answer: 172.20.2.12
      enabled: true
    - domain: jupiter.yaf.internal
      answer: 172.20.4.10
      enabled: true
    - domain: mars.yaf.internal
      answer: 172.20.4.111
      enabled: true
    - domain: saturn.yaf.internal
      answer: 172.20.4.112
      enabled: true
    - domain: uranus.yaf.internal
      answer: 172.20.4.13
      enabled: true
    - domain: eris.yaf.internal
      answer: 172.20.4.14
      enabled: true
    - domain: leda.yaf.internal
      answer: 172.20.4.115
      enabled: true
    - domain: ananke.yaf.internal
      answer: 172.20.4.16
      enabled: true
    - domain: inky.yaf.internal
      answer: 172.20.6.50
      enabled: true
    # shodnenskaya4 (21)
    - domain: mts.sh4.outer
      answer: 192.168.1.1
      enabled: true
    - domain: router.sh4.local
      answer: pluto.sh4.local
      enabled: true
    - domain: pluto.sh4.local
      answer: 172.21.1.1
      enabled: true
    - domain: pluto.local
      answer: pluto.sh4.local
      enabled: true
    - domain: '*.app.sh4.local'
      answer: ixion.sh4.local
      enabled: true
    - domain: ixion.sh4.local
      answer: 172.20.13.21
      enabled: true
    - domain: ixion.local
      answer: ixion.sh4.local
      enabled: true
    - domain: '*.ixion.sh4.local'
      answer: ixion.sh4.local
      enabled: true
    # shodnenskaya5 (22)
    - domain: mts.sh5.external
      answer: 192.168.1.1
      enabled: true
    - domain: router.sh5.internal
      answer: haumea.sh5.internal
      enabled: true
    - domain: haumea.sh5.internal
      answer: 172.22.0.1
      enabled: true
    - domain: '*.app.sh5.internal'
      answer: makemake.sh5.internal
      enabled: true
    - domain: makemake.sh5.internal
      answer: 172.22.2.10
      enabled: true
    - domain: makemake.internal
      answer: makemake.sh5.internal
      enabled: true
    - domain: '*.makemake.sh5.internal'
      answer: makemake.sh5.internal
      enabled: true
    # web
    - domain: proxima.web.external
      answer: 185.133.173.100
      enabled: true
    - domain: proxima.external
      answer: proxima.web.external
      enabled: true
    - domain: adguard.app.web.external
      answer: 172.29.172.100
      enabled: true
    - domain: share.app.web.external
      answer: 172.29.172.101
      enabled: true
    - domain: webdav.app.web.external
      answer: 172.29.172.102
      enabled: true