networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.15.0/24
          gateway: 198.19.15.1

volumes:
  ansiblewebui_data:
  ansiblewebui_playbook:

services:
  ansiblewebui:
    container_name: ansiblewebui
    image: oxlorg/ansible-webui:latest
    hostname: ansiblewebui
    volumes:
      - ansiblewebui_data:/data
      - ansiblewebui_playbook:/playbook
    ports:
      - 31520:8000
    networks:
      net:
        ipv4_address: 198.19.15.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://198.19.15.2:8000"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
