vasilkovo:
  children:
    linux-vasilkovo:
    windows-vasilkovo:

linux-vasilkovo:
  children:
    server-linux-vasilkovo:
    desktop-linux-vasilkovo:

windows-vasilkovo:
  children:
    desktop-windows-vasilkovo:

# servers
server-linux-vasilkovo:
  children:
    metal-server-linux-vasilkovo:

metal-server-linux-vasilkovo:
  hosts:
    io.vas.internal:
    europa.vas.internal:

#desktops                
desktop-windows-vasilkovo:
  hosts:
    elara.vas.internal:

desktop-linux-vasilkovo:
  hosts: