yasenevof:
  children:
    linux-yasenevof:
    windows-yasenevof:

linux-yasenevof:
  children:
    server-linux-yasenevof:
    desktop-linux-yasenevof:

windows-yasenevof:
  children:
    desktop-windows-yasenevof:

# servers
server-linux-yasenevof:
  children:
    metal-server-linux-yasenevof:

metal-server-linux-yasenevof:
  hosts:
    ariel.yaf.internal:

#desktops                
desktop-windows-yasenevof:
  hosts:

desktop-linux-yasenevof:
  hosts: