networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.16.0/24
          gateway: 198.19.16.1

volumes:
  config:

services:
  firefox:
    image: lscr.io/linuxserver/firefox:kasm
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1999
      - PGID=100
      - TZ=Europe/Moscow
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - config:/config
    ports:
      - 31620:3000
    shm_size: "256mb"
    networks:
      net:
        ipv4_address: 198.19.16.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://198.19.16.2:3000"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: no
