networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.11.0/24
          gateway: 198.19.11.1

volumes:
  postgres-data:
  redis_data:
  config:
  data:
  
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:30.0.11
    container_name: nextcloud
    hostname: nextcloud
    environment:
      - PUID=1999
      - PGID=2000
      - TZ=Europe/Moscow
      - UMASK=007
    volumes:
      - config:/config
      - data:/data
      - ${DATA_FILES_ADMIN}:/data/admin
      - ${DATA_FILES_LESHA}:/data/lesha
      - ${DATA_PHOTO_LESHA}:/externaldata/photo/users/lesha:ro
      - ${DATA_VIDEO_FAMILY}:/externaldata/video/family:ro
      - ${DATA_DOCUMENTS_LESHA}:/externaldata/documents/users/lesha
    ports:
      - 31124:443
    depends_on:
      redis:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
    networks:
      net:
        ipv4_address: 198.19.11.2
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=10", "http://198.19.11.2"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped

  postgresdb:
    image: pgautoupgrade/pgautoupgrade:latest
    container_name: nextcloud-postresdb
    hostname: postgresdb
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: psql -U nextcloud -d nextcloud -c "SELECT 1;"
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      net:
        ipv4_address: 198.19.11.3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped

  redis:
    image: redis:alpine    
    container_name: nextcloud-redis
    hostname: redis
    volumes:
      - redis_data:/data
    networks:
      net:
        ipv4_address: 198.19.11.4
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3  
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
