networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.93.0/24
          gateway: 198.19.93.1

volumes:
  ml_models:
  postgredb_data:

services:
  server:
    container_name: immich-server
    hostname: server
    image: ghcr.io/immich-app/immich-server:release
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 39320:2283
    volumes:
      - ${PHOTO_DIR}:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Moscow
      - DB_USERNAME=immich
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=immich
    networks:
      net:
        ipv4_address: 198.19.93.2
    depends_on:
      redis:
        condition: service_healthy
      postgredb:
        condition: service_healthy
    healthcheck:
        disable: false
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped

  ml:
    container_name: immich-ml
    hostname: ml
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ml_models:/cache
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - TZ=Europe/Moscow
    networks:
      net:
        ipv4_address: 198.19.93.3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped

  redis:
    container_name: immich-redis
    hostname: redis
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    environment:
      - TZ=Europe/Moscow
    networks:
      net:
        ipv4_address: 198.19.93.4
    healthcheck:
      test: redis-cli ping || exit 1
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped

  postgredb:
    container_name: immich-postgredb
    hostname: postgredb
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=immich
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS='--data-checksums'
    volumes:
      - postgredb_data:/var/lib/postgresql/data
    shm_size: 128mb
    networks:
      net:
        ipv4_address: 198.19.93.5
    healthcheck:
      test: psql -U immich -d immich -c "SELECT 1;"
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
